### ISSUE TITLE
ps -ef doesn't work on OpenBSD

### ISSUE THREAD

**Issue by ljhanson** [ivakyb/fish_ssh_agent#2]
BSD's don't have f option for ps.  So function __ssh_agent_is_started fails.

ps: unknown option -- f
usage: ps [-AaceHhjkLlmrSTuvwx] [-M core] [-N system] [-O fmt] [-o fmt] [-p pid]
          [-t tty] [-U username] [-W swap]

**Comment by kuvaldini** [comment]
I believe you can install GNU coreutils with ps (may be it is named gps) or find another proper flag
