### ISSUE TITLE
rofi doesn't pass fish environment vars

### ISSUE THREAD

**Issue by Trollwut** [ivakyb/fish_ssh_agent#3]
Hey there!

I'm not sure if this is the right place for it.

First of all, thanks for your script! Finally I got one `ssh-agent` running for my whole fish system.

I use *i3-wm* and use `rofi` as my application launcher. If I start `keepassxc` via `rofi`, it doesn't know about the started `ssh-agent`.

Though if I run `keepassxc` via terminal, it just works as intended.

Is there something I'm missing?

It seems like `rofi` doesn't know about the environment variables set by fish.

**Comment by ivakyb** [comment]
Hi. I'm Glad to hear feedback from you.

> It seems like `rofi` doesn't know about the environment variables set by fish.

Right. Only processes forked from fish inherits its environment.   

There are multiple ways to make any program know your environment.  
I believe the simplest in your case is to run any program which requires SSH_AGENT throurh `fish`, like:
```
fish -c program
```

On Mac
```
fish -c /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
```
or
```
fish -c 'open /Applications/KeePassXC.app'
```

On Linux you'll want to edit `.desktop`-files.

On any system you can create own script 
```
#!/usr/bin/env fish
myprogram
```
and make it executable with `chmod +x launch-myprog`

I know nothing specific to `rofi`.

<sub>I am sorry for the late answer</sub>
